SigNoz/charts

- .github/workflows/release.yaml
> ci(release): workflow for releasing helm charts

- charts/signoz/Chart.yaml
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/values.yaml
Signed-off-by: Prashant Shahi <me@prashantshahi.dev>
> chore: 📌 bump up image version tags

- README.md
- charts/signoz/README.md
Resolves #6 
/cc @pranay01
/cc @ankitnayan
> docs(contributing): 📝 Add main README and signoz chart README

- charts/alertmanager/templates/serviceaccount.yaml
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/frontend/deployment.yaml
- charts/signoz/templates/frontend/serviceaccount.yaml
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector-metrics/serviceaccount.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/templates/otel-collector/serviceaccount.yaml
- charts/signoz/templates/query-service/serviceaccount.yaml
- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/values.yaml
- use imagePullSecrets for signoz charts
- registry and image helper template changes
> chore: 🔧 support custom registry and helper template changes

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
Support clickhouse cluster with shards and replicas (distributed)
> chore(clickhouse): ✨ support cluster shards and replicas

- charts/signoz/templates/frontend/config.yaml
> chore: 🔧 frontend nginx config

- charts/clickhouse/templates/clickhouse-operator/deployment.yaml
- charts/clickhouse/values.yaml
- charts/signoz/templates/_clickhouse.tpl
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/values.yaml
> chore: 🔧 External Clickhouse support and OtelCollector env fixes

- charts/signoz/Chart.yaml
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/otel-collector-metrics/config.yaml
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/values.yaml
> OTel collector config fixes and new chart release

- charts/signoz/Chart.yaml
Further to PR #33, bumping Chart minor version for a new release
> chore(release): 🔖 Bump up signoz to 0.0.16

- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/alertmanager/statefulset.yaml
- charts/signoz/values.yaml
Related to https://github.com/SigNoz/signoz/pull/1238
> chore(alertmanager): wrench use query-service internal port

- charts/signoz/templates/query-service/service.yaml
> chore: 🔧 query-service expose internal port

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
- release: bump up signoz to 0.0.17
- pin 0.8.1 signoz
- pin 0.45.1-0.2 otelcollector and otelcollector metrics
- update default values.yaml
- update README docs
> chore(release): 🔖 release 0.0.17 and deploy changes

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
> chore(clickhouse-release): 🔖 Use service template and bump up clickhouse to 16.0.6

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> chore(release): 🔖 Bump up signoz to 0.1.0 and pin latest versions of signoz and otel collector

- charts/signoz/Chart.yaml
- charts/signoz/templates/alertmanager/services.yaml
- charts/signoz/templates/alertmanager/statefulset.yaml
> fix(alertmanager): 🚑 fix replicaCount comparision type issue

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance.yaml
Fixes https://github.com/SigNoz/signoz/issues/1437
> fix: 🚀 disables TTL moves on insert and only run in background

- charts/signoz/values.yaml
> chore: 🔧 use signoz.io annotation for scraping metrics

- charts/signoz/Chart.yaml
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
> fix:  include otel ports in otel collector and metrics pods

- charts/signoz/Chart.yaml
- charts/signoz/templates/otel-collector-metrics/clusterrole.yaml
- charts/signoz/templates/otel-collector-metrics/clusterrolebinding.yaml
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/clusterrole.yaml
- charts/signoz/templates/otel-collector/clusterrolebinding.yaml
- charts/signoz/templates/otel-collector/daemonset.yaml
- charts/signoz/values.yaml
> Logs related changes and release signoz chart v0.3.0

- charts/clickhouse/Chart.yaml
- charts/clickhouse/crds/clickhouseinstallations.clickhouse.altinity.com.yaml
- charts/clickhouse/crds/clickhouseinstallationtemplates.clickhouse.altinity.com.yaml
- charts/clickhouse/crds/clickhouseoperatorconfigurations.clickhouse.altinity.com.yaml
- charts/clickhouse/templates/_helper.tpl
- charts/clickhouse/templates/clickhouse-operator/clusterrole.yaml
- charts/clickhouse/templates/clickhouse-operator/clusterrolebinding.yaml
- charts/clickhouse/templates/clickhouse-operator/deployment.yaml
- charts/clickhouse/templates/clickhouse-operator/service.yaml
- charts/clickhouse/values.yaml
> Fix RBAC issue, clickhouse-operator upgrade and chart release

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance.yaml
- charts/clickhouse/templates/clickhouse-operator/configmap.yaml
- charts/clickhouse/templates/clickhouse-operator/deployment.yaml
- charts/clickhouse/values.yaml
- logging option templates and remove trailing spaces
- include log volumeClaim template comment
- include config checksum annotation
> clickhouse logging option template and other changes

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_helpers.tpl
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-agent/service.yaml
- charts/k8s-infra/templates/otel-deployment/clusterrole.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/values.yaml
> chore: 🚀 configurations for SaaS

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-operator/namespace.yaml
> create custom namespace for clickhouse chart

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> signoz chart v0.4.2 release

- charts/signoz/Chart.yaml
- charts/signoz/templates/_helpers.tpl
> fix for the redundant nodeport issue

- charts/signoz/Chart.yaml
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/cert-issuer.yaml
- charts/signoz/values.yaml
Related to https://github.com/SigNoz/signoz.io/issues/581
> Template for Let's encrypt ClusterIssuer

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_config.tpl
- charts/k8s-infra/values.yaml
> remove unsupported metadata fields and improve k8sattributes processor

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_helpers.tpl
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/templates/secret.yaml
- charts/k8s-infra/values.yaml
> Support TLS secrets for OTLP exporter and release k8s-infra v0.2.2

- charts/signoz/templates/frontend/configmap.yaml
Fixes https://github.com/SigNoz/signoz/issues/1881
> fix: proxy_read_timeout updated in nginx conf

- charts/signoz/values.yaml
Same as https://github.com/SigNoz/signoz/pull/1925 for charts
> Increase dimensions_cache_size for signozspanmetrics processor

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-agent/serviceaccount.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/templates/otel-deployment/service.yaml
> resolve service account create issue and other fixes

- charts/k8s-infra/values.yaml
- charts/signoz/values.yaml
> chore: 🔧 k8sattribute/resourceattribute processors

- charts/signoz/values.yaml
> chore: 🔧 include relabel_configs and related prometheus changes

- charts/k8s-infra/templates/_helpers.tpl
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/values.yaml
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/values.yaml
> chore: 🔧 include clusterName and envvar templates

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/_helper.tpl
- charts/clickhouse/values.yaml
- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_helpers.tpl
- charts/k8s-infra/templates/otel-agent/tests/test-connection.yaml
- charts/k8s-infra/templates/otel-deployment/tests/test-connection.yaml
- charts/k8s-infra/values.yaml
- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/frontend/tests/test-connection.yaml
- charts/signoz/templates/query-service/tests/test-connection.yaml
- charts/signoz/values.yaml
> resolve global registry issues

- charts/signoz/Chart.yaml
- charts/signoz/values.yaml
> rename k8s labels in relabel_configs

- charts/k8s-infra/templates/_helpers.tpl
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
[Slack Message](https://signoz-community.slack.com/archives/C03VAQPFQ7L/p1673592353968269)
> fix: 🚑  otel resource attr env fixes

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_config.tpl
- charts/k8s-infra/templates/_helpers.tpl
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/values.yaml
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/values.yaml
> k8sattribute fixes with related hostmetrics and clusterrole changes

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
- charts/signoz/templates/alertmanager/statefulset.yaml
- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/values.yaml
- Persistence changes in clickhouse, alertmanager, query-service
- Bump up clickhouse chart to 23.8.1
> Support existing PVC and disabled persistence

- .github/workflows/CODEOWNERS
To follow and review the config changes because I find myself reviewing some commits late and catching the potential issues when they are already merged.
> Add myself

- .github/workflows/CODEOWNERS
> chore: 👥  update CODEOWNERS

- charts/clickhouse/templates/clickhouse-operator/deployment.yaml
- charts/clickhouse/values.yaml
> feat(clickhouse): ✨ include pod level configurations for operator

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/_helper.tpl
- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
Fixes #150
Related: https://github.com/SigNoz/charts/issues/148#issuecomment-1399845922
> feat(clickhouse): ✨ custom configuration files support

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance/serviceaccount.yaml
- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/otel-agent/serviceaccount.yaml
- charts/k8s-infra/templates/otel-deployment/serviceaccount.yaml
> resolve indentation issues of image pull secrets in service accounts

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- charts/clickhouse/templates/clickhouse-operator/deployment.yaml
- charts/clickhouse/values.yaml
- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/values.yaml
- charts/signoz/templates/alertmanager/statefulset.yaml
- charts/signoz/templates/frontend/deployment.yaml
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/values.yaml
> chore: 🔧 Add priorityClassName for all components

- charts/signoz/README.md
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/values.yaml
> chore: 🔧 Add low cardinal exception grouping configuration

- charts/signoz/Chart.yaml
- charts/signoz/values.yaml
> chore: 🔧 remove init container from signoz apm metrics

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.11.2

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance/storage-class.yaml
- charts/clickhouse/values.yaml
- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/values.yaml
> feat: ✨ support for GKE Autopilot

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/values.yaml
- charts/signoz/values.yaml
> chore(otel): include sources in pod association

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.13.1

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/_helper.tpl
- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
> clickhouse: custom init containers support

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
Fixes https://github.com/SigNoz/signoz/issues/2532
> feat(clickhouse): ✨ support for Google Cloud Storage (GCS)

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.14.1

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
Please deploy to saas after merging.
> Release/signoz 0.14.2

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/values.yaml
- charts/signoz/values.yaml
> Release/k8s-infra 0.7.2

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/values.yaml
This PR adds id and output keys to log parsing operators.
> Fix: add id and output keys in log operators.

- charts/signoz/templates/frontend/hpa.yaml
- charts/signoz/templates/otel-collector/hpa.yaml
Update `apiVersion` for `HorizontalPodAutoscaler`.
> feat(hpa): update apiVersion

- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/values.yaml
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/values.yaml
> chore: 🔧 support for custom envs in otel-collectors of signoz/k8s-infra

- charts/signoz/values.yaml
PR for https://github.com/SigNoz/signoz/issues/2700
DON't merge this before signoz-otel-collector > 0.76 is released
> feat: add default parser for logs

- charts/k8s-infra/values.yaml
- charts/signoz/values.yaml
https://github.com/SigNoz/signoz/commit/93c9138fe1104c1006d2570f0f761da722ee0cc2 for the charts. Should have updated it along with the extraArgs.
> Update resourcedetection refs for GCP

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.17.0

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/values.yaml
> Release/k8s infra 0.9.0

- .github/workflows/release.yaml
> ci(release-workflow): 👷 bump up version of chart-releaser-action and pin Helm

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.18.0

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_config.tpl
- charts/k8s-infra/templates/secret.yaml
- charts/k8s-infra/values.yaml
> feat(tls): ✨ support for CA in K8s-Infra

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.19.1

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.20.0

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.21.1

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.21.3

- charts/signoz/Chart.yaml
- charts/signoz/templates/frontend/configmap.yaml
This is for fixing live tail issue
> fix: disable proxy buffering and cache

- charts/signoz/Chart.yaml
- charts/signoz/templates/frontend/configmap.yaml
Fix as requested here https://github.com/SigNoz/charts/pull/277#issuecomment-1687500977
> fix: nginx config updated only for live tail

- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/templates/query-service/tests/test-connection.yaml
- charts/signoz/values.yaml
> chore: 🔧 use query-service healthcheck instead of version

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/values.yaml
Fixes #263
- more configurations for probes
- documentation for signoz chart configurations
> chore: update query-service probes and update docs

- charts/clickhouse/README.md
Propose settings for clickhouse chart - necesity to whitelist IP address range for kubernetes nodes
> Create README.md for Clickhouse chart with important advice

- charts/signoz/templates/query-service/statefulset.yaml
> chore(query-service): 🔧 include prefer-delta flag

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.25.0

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.25.1

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.25.3

- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/values.yaml
> chore(query-service): :wrench: additional arguments for command line

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.27.0

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.27.1

- charts/signoz/README.md
- charts/signoz/values.yaml
> chore(otel-collector): 🔧 enable httpreceiver for heroku logs

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.28.0

- charts/signoz/values.yaml
> chore(otel-collector): 🔧 enable httpreceiver for JSON logs

- charts/signoz/Chart.yaml
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/templates/otel-collector/schema-migrator-job.yaml
- charts/signoz/values.yaml
> chore: 🔧 enabled flag for schema-migrator

- charts/signoz/values.yaml
Bying some time as I suspect this is the issue.
> feat: setting num consumers to 1

- charts/signoz/values.yaml
Fixes https://github.com/SigNoz/signoz/issues/3778
> feat: default trace_parser updated

- charts/signoz/README.md
- charts/signoz/values.yaml
Only to be merged after https://github.com/SigNoz/signoz-otel-collector/pull/214 is released
> fix: rename httpreceiver to httplogreceiver

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.29.0

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.29.1

- charts/signoz/values.yaml
Update trace parser.
previously it considered something like this as well `x-trace-id` which should be considered.
> fix: trace_parser updated

- charts/signoz/values.yaml
Removing num_consumers as we have an otel collector release done.
> fix: remove sending_queue num_consumers

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- ct.yaml
> ci(lint-install): :construction_worker: update GH workflows and ct configuration

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
> chore(clickhouse): include reclaimPolicy to Retain in CHI

- charts/k8s-infra/templates/_config.tpl
- charts/k8s-infra/values.yaml
- charts/signoz/values.yaml
> feat(k8s-infra): ✨ Support for whitelist in log collection

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/values.yaml
> Release/k8s infra 0.10.0

- charts/signoz/Chart.yaml
- charts/signoz/templates/_helpers.tpl
> chore(migrator-job): remove dependency of name suffix with AppVersion

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.30.3

- charts/signoz/Chart.yaml
- charts/signoz/templates/otel-collector/schema-migrator-job.yaml
> chore(schema-migrator): remove app/chart versions from job labels

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.30.5

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
More context: https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1701124166307409?thread_ts=1700184882.205159&cid=C01HWQ1R0BC
> fix(k8s-infra): include otel-auth security context

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/otel-agent/ingress.yaml
This is a copy-paste of the deployment ingress template with the values changed
Fixes #341
> feat: add template for agent ingress

- charts/signoz/Chart.yaml
- charts/signoz/templates/_helpers.tpl
- charts/signoz/templates/otel-collector-metrics/deployment.yaml
- charts/signoz/templates/otel-collector/deployment.yaml
- charts/signoz/values.yaml
groundnuty/k8s-wait-for:v2.0 deprecates K8s ver less than v1.23
> fix!: Support init on ARM64 and update groundnuty/k8s-wait-for

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.30.7

- charts/clickhouse/values.yaml
- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.31.1

- charts/clickhouse/values.yaml
- charts/signoz/values.yaml
Fixes https://github.com/SigNoz/signoz/issues/4224
> feat: upgrade clickhouse to 23.11.1

- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
- charts/signoz/templates/alertmanager/statefulset.yaml
- charts/signoz/templates/frontend/deployment.yaml
- charts/signoz/templates/otel-collector/schema-migrator-job.yaml
- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/values.yaml
> chore: annotation and hook weights

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.32.0

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.32.1

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.32.2

- charts/clickhouse/templates/clickhouse-operator/configmaps/etc-configd-files.yaml
- charts/clickhouse/values.yaml
- charts/signoz/values.yaml
high volume tables - 7 days
moderate volume tables - 15 days
low volume tables - 30 days
> Update system log tables TTL

- charts/signoz/templates/_clickhouse.tpl
Fixes #371, #367
https://go.dev/play/p/vM1M04_LzR_O
> Use default format for variables

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_config.tpl
> fix(k8s-infra): remove debug comment from otel-deployment config template

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/otel-agent/tests/test-connection.yaml
- charts/k8s-infra/templates/otel-deployment/tests/test-connection.yaml
> chore(k8s-infra): update test connection files

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.33.1

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_helpers.tpl
- charts/k8s-infra/templates/apikey-secret.yaml
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/templates/tls-secret.yaml
- charts/k8s-infra/values.yaml
> chore(k8s-infra): use secrets for SigNoz API key

- charts/signoz/templates/_clickhouse.tpl
- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/values.yaml
> chore(signoz): args support for migrations

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_helpers.tpl
> fix(k8s-infra): update apikey secret name

- charts/signoz/templates/query-service/configmap.yaml
- charts/signoz/templates/query-service/statefulset.yaml
- charts/signoz/values.yaml
> feat(query-service): support for cache

- charts/signoz/Chart.yaml
- charts/signoz/templates/schema-migrator/migrations-init.yaml
- charts/signoz/templates/schema-migrator/migrations-upgrade.yaml
> fix(schema-migrator): shardsCount typo in script

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.36.0

- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
- charts/signoz/values.yaml
Closes:
- #245
I'm open to feedback and appreciate any guidance you can provide as I continue to learn and improve. Thank you for your time and consideration.
> Templatizing histogram operators URL

- charts/signoz/README.md
- charts/signoz/templates/alertmanager/services.yaml
- charts/signoz/templates/frontend/service.yaml
- charts/signoz/templates/otel-collector-metrics/service.yaml
- charts/signoz/templates/otel-collector/service.yaml
- charts/signoz/templates/query-service/service.yaml
- charts/signoz/values.yaml
Added Support for Custom Labels, so users can add labels as per requirements, Intended to fixes #395 .
> Add Supports for Custom Labels for all signoz defined services

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.37.0

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.37.1

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.38.0

- charts/signoz/templates/schema-migrator/migrations-init.yaml
- charts/signoz/templates/schema-migrator/migrations-upgrade.yaml
- charts/signoz/values.yaml
Related https://github.com/SigNoz/signoz-otel-collector/pull/293
> chore(schema-migrator): support for replication

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> chore(signoz): 📌 pin versions: SigNoz 0.43.0, OtelCollector 0.88.20

- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
- charts/signoz/values.yaml
> feat: Extract initContainer.udf.command as values from clickhouse chart

- charts/signoz/Chart.yaml
- charts/signoz/templates/schema-migrator/migrations-init.yaml
- charts/signoz/templates/schema-migrator/migrations-upgrade.yaml
- charts/signoz/values.yaml
> chore(schema-migrator): wait for all ClickHouse replicas to be ready

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.40.0

- .github/workflows/release.yaml
- ct.yaml
> chore(lint): remove deprecated bitnami pre-2022

- charts/clickhouse/Chart.yaml
> chore(release): 🔖 Bump up clickhouse to 24.1.0

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/templates/alertmanager/statefulset.yaml
- charts/signoz/values.yaml
> chore(alertmanager): support for additional environments

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> chore(signoz): 📌 pin versions: SigNoz Alertmanager 0.23.5

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.43.0

- charts/signoz/values.yaml
chnage cache duration to a week as discussed in workation
> fix: change cache to 1 week

- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/templates/_config.tpl
- charts/k8s-infra/templates/_helpers.tpl
- charts/k8s-infra/templates/otel-agent/daemonset.yaml
- charts/k8s-infra/templates/otel-deployment/deployment.yaml
- charts/k8s-infra/values.yaml
Generated processor config for `otel-agent` and `otel-deployment`.
```yaml
processors:
resource/deployenv:
attributes:
- action: insert
key: deployment.environment
value: ${env:DEPLOYMENT_ENVIRONMENT}
```
> feat(k8s-infra): introduce deployment.environment global var

- CONTRIBUTING.md
Added user_count and spawn_rate options to hotRod load data command. Without these I was getting InternalServerError response.
> fix: added user_count and spawn_rate options to hotRod load data command

- charts/signoz/Chart.yaml
> chore(release): 🔖 Bump up signoz to 0.45.0

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
- Pin versions: SigNoz 0.49.1, SigNoz OtelCollector 0.102.2
- Bump up signoz to 0.45.1 
> Release/signoz 0.45.1

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- charts/clickhouse/values.yaml
- clickhouse: support additional Volumes and VolumeMounts
- bump up clickhouse chart to 24.1.2
----
> chore(clickhouse): support additional Volumes and VolumeMounts

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
- chore(signoz): 📌 pin versions: SigNoz 0.50.0 
- chore(release): 🔖 Bump up signoz to 0.46.0
> Release/signoz 0.46.0

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
- set move_factor to 0, enable prefer_not_to_merge 
- bump up clickhouse to 24.1.4
> chore(clickhouse): set move_factor to 0, enable prefer_not_to_merge 

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
- chore(signoz): 📌 pin versions: SigNoz 0.50.0 
- chore(release): 🔖 Bump up signoz to 0.46.0
> Release/signoz 0.47.0

- .github/workflows/test.yaml
- charts/k8s-infra/Chart.yaml
- charts/k8s-infra/values.yaml
- charts/signoz-otel-gateway/.helmignore
- charts/signoz-otel-gateway/Chart.lock
- charts/signoz-otel-gateway/Chart.yaml
- charts/signoz-otel-gateway/templates/_helpers.tpl
- charts/signoz-otel-gateway/templates/config.yaml
- charts/signoz-otel-gateway/templates/deployment.yaml
- charts/signoz-otel-gateway/templates/ingress.yaml
- charts/signoz-otel-gateway/templates/secrets.yaml
- charts/signoz-otel-gateway/templates/service.yaml
- charts/signoz-otel-gateway/templates/serviceaccount.yaml
- charts/signoz-otel-gateway/values.yaml
- ct.yaml
- Add `signoz-otel-gateway` chart
> feat(signoz-otel-gateway): add signoz-otel-gateway chart

- .github/workflows/release.yaml
- charts/signoz/Chart.lock
- charts/signoz/Chart.yaml
- charts/signoz/values.yaml
- ct.yaml
- Add signoz-otel-gateway as a dependency on signoz
> feat(signoz): add signoz-otel-gateway as a dependency

- charts/signoz/README.md
- charts/signoz/values.yaml
> feat: update otel collector image

- charts/signoz/README.md
- charts/signoz/values.yaml
update otel collector image to 0.102.6
> fix: update otel collector image to 0.102.6

- charts/signoz/README.md
- charts/signoz/values.yaml
update otel collector image to 0.102.7
> feat: update otel collector image to v0.102.7

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
> Release/signoz 0.51.0

- charts/signoz/Chart.lock
- charts/signoz/Chart.yaml
- signoz: pin charts: clickhouse 24.1.7
- release: bump up signoz to 0.51.1
> Release/signoz 0.51.1

- charts/signoz/Chart.yaml
- charts/signoz/README.md
- charts/signoz/values.yaml
- release SigNoz v0.54.0
- bump up SigNoz OtelCollector v0.102.8
> Release/signoz 0.52.0

- charts/signoz/Chart.lock
- charts/signoz/Chart.yaml
- charts/signoz/templates/frontend/configmap.yaml
- charts/signoz/templates/frontend/deployment.yaml
- charts/signoz/templates/frontend/hpa.yaml
- charts/signoz/templates/frontend/ingress.yaml
- charts/signoz/templates/frontend/keda-autoscaler.yaml
- charts/signoz/templates/frontend/service.yaml
- charts/signoz/templates/frontend/serviceaccount.yaml
- charts/signoz/values.yaml
> feat(signoz): make frontend optional
