SigNoz/charts

charts/clickhouse/Chart.yaml
charts/clickhouse/values.yaml
charts/signoz/templates/frontend/deployment.yaml
charts/signoz/templates/otel-collector-metrics/deployment.yaml
charts/signoz/templates/otel-collector-metrics/service.yaml
charts/signoz/templates/otel-collector-metrics/serviceaccount.yaml
charts/signoz/templates/otel-collector/deployment.yaml
charts/signoz/templates/otel-collector/service.yaml
charts/signoz/templates/otel-collector/serviceaccount.yaml
charts/signoz/templates/query-service/statefulset.yaml
charts/signoz/values.yaml

- use overrode full name for zookeeper for ClickHouse
- use a service account for SigNoz charts
- add service type template for Otel Collector and metrics

chore: 🔧 add service account and service type template for SigNoz charts

---

charts/signoz/templates/frontend/ingress.yaml

networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22
Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19.

Migrate to stable Ingress API

---

charts/signoz/README.md
charts/signoz/templates/frontend/ingress.yaml
charts/signoz/templates/query-service/ingress.yaml
charts/signoz/values.yaml

I was deploying Signoz via Helm Chart however not being able to define ingress classname on the frontend/query service made it so that external DNS was unable to process that DNS. Allowing this would be super helpful :)

Allow Ingress Class Name frontend/query service

---

charts/signoz/Chart.yaml
charts/signoz/templates/frontend/config.yaml

Default nginx proxy HTTP protocol is 1.0, which causes 426 Upgrade Errors when communicating with the query-service in an Istio environment.
Closes https://github.com/SigNoz/charts/issues/53
Signed-off-by: Nick Burrett <nick@sqrt.co.uk>

fix(frontend): change HTTP proxy protocol from 1.0 to 1.1 to stop 426 error

---

charts/clickhouse/Chart.yaml
charts/clickhouse/crds/clickhouse-operator-install.yaml

- upgrade clickhouse operator to 0.19.0
- use `signoz.io/*` annotations for scraping operator metrics

bump up clickhouse operator version

---

charts/clickhouse/templates/_helper.tpl
charts/clickhouse/templates/clickhouse-instance.yaml
charts/clickhouse/values.yaml
charts/signoz/templates/_helpers.tpl
charts/signoz/templates/alertmanager/statefulset.yaml
charts/signoz/templates/query-service/statefulset.yaml
charts/signoz/values.yaml

This PR resolves the issue which was observered when users tried to install SigNoz on K8s cluster without a default storage class.
- storage class global value which applies to all PVC
- add global value for image registry
**Example**
```bash
$ kubectl get storageclass
NAME       PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  48m
```
As we can see above, we do not have any default storage class.
So, we will use the following `override-values.yaml`:
```yaml
global:
storageClass: standard
clickhouse:
cloud: others
```

storage class related improvements and other changes

---

charts/signoz/values.yaml

This processor has been deprecated and will cause a crash loop if deploy
is attempted.
https://github.com/open-telemetry/opentelemetry-collector/blob/ce603c9209ffeae1c677a228e3c79f2e3cc54fbc/CHANGELOG.md#-breaking-changes--38

Remove Otel Collector Queued Retry Processor

---

charts/signoz/templates/_helpers.tpl
charts/signoz/values.yaml

Hi,
We were facing issue when we defined otelCollector's service type as NodePort. We were desiring to add nodePort statically but it was assigned to ports dynamically. So I added feature with @canerturkaslan to the _helper.tpl as you can see from our commit. 
For example if you want to assign static nodePort you can give values.yaml like below:
```yaml
otelCollector:
service:
type: NodePort
ports:
otlp:
nodePort: 30900
targetPort: otlp
protocol: TCP
```

add nodePort feature to _helpers.tpl

---

charts/signoz/templates/_helpers.tpl
charts/signoz/templates/frontend/config.yaml
charts/signoz/values.yaml

Hi,
During our load tests to the signoz we faced with a serious problem which is inaccessibility of the frontend service. We troubleshooted it and saw that we were getting errors from frontend's nginx. So we added some parameters to the signoz-frontend configMap and solved the issue. Because of that we made it configurable.
Also @canerturkaslan added this values example to the values.yaml

Frontend nginx cm customize feature

---

charts/k8s-infra/.helmignore
charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/NOTES.txt
charts/k8s-infra/templates/_helpers.tpl
charts/k8s-infra/templates/otel-agent/clusterrole.yaml
charts/k8s-infra/templates/otel-agent/clusterrolebinding.yaml
charts/k8s-infra/templates/otel-agent/configmap.yaml
charts/k8s-infra/templates/otel-agent/daemonset.yaml
charts/k8s-infra/templates/otel-agent/service.yaml
charts/k8s-infra/templates/otel-agent/serviceaccount.yaml
charts/k8s-infra/templates/otel-agent/tests/test-connection.yaml
charts/k8s-infra/templates/otel-deployment/clusterrole.yaml
charts/k8s-infra/templates/otel-deployment/clusterrolebinding.yaml
charts/k8s-infra/templates/otel-deployment/configmap.yaml
charts/k8s-infra/templates/otel-deployment/deployment.yaml
charts/k8s-infra/templates/otel-deployment/ingress.yaml
charts/k8s-infra/templates/otel-deployment/service.yaml
charts/k8s-infra/templates/otel-deployment/serviceaccount.yaml
charts/k8s-infra/templates/otel-deployment/tests/test-connection.yaml
charts/k8s-infra/values.yaml

This PR introduces `k8s-infra` chart which makes it very easy to collect metrics and logs from any external Kubernetes cluster.
After the PR is merged, we can install it by running the command below:
```bash
helm install my-release signoz/k8s-infra  \
--set otelCollectorEndpoint=<IP-or-Endpoint-of-SigNoz-OtelCollector>:4317
```
If `otelCollectorEndpoint` is not set, it will default to `my-release-signoz-otel-collector.platform.svc.cluster.local:4317`.
- By default, logs from `kube-system` is disabled. To enable, comment out specific section from `filelog/k8s.exclude` in `otelAgent`.
- By default, logs from hotrod sample app is disabled. To enable, comment out specific section from `filelog/k8s.exclude` in `otelAgent`.
- It can be used to send captured metrics and logs to any OpenTelemetry …

feat: ✨ introduce k8s-infra chart

---

charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/_helpers.tpl
charts/k8s-infra/templates/namespace.yaml
charts/k8s-infra/templates/otel-agent/configmap.yaml
charts/k8s-infra/templates/otel-agent/daemonset.yaml
charts/k8s-infra/templates/otel-agent/service.yaml
charts/k8s-infra/templates/otel-agent/serviceaccount.yaml
charts/k8s-infra/templates/otel-deployment/configmap.yaml
charts/k8s-infra/templates/otel-deployment/deployment.yaml
charts/k8s-infra/templates/otel-deployment/ingress.yaml
charts/k8s-infra/templates/otel-deployment/service.yaml
charts/k8s-infra/templates/otel-deployment/serviceaccount.yaml
charts/k8s-infra/values.yaml
charts/signoz/values.yaml

- custom namespace support for k8s-infra chart
- otel endpoint automatically generated when installed as dependency of signoz chart
- k8s-infra patch release: `0.1.3`

k8s-infra chart improvements

---

charts/k8s-infra/values.yaml
charts/signoz/values.yaml

The current config is probably taken directly from examples as is but the default and preferred way is to override the existing keys https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/common#attribute-collections. The `resourcedetection` configured with env adds `service.instance.id` and any data that is already received which has that attribute will not be overridden with the given config. This is also the reason why other metrics including up couldn't be written to DB hence not showing up in dashboards. There is an ongoing effort to stabilize and spec'd out the details of OTLP -> Prom data conversion and we should update parts of our exporter which will be addressed another issue.

fix: use default override setting

---

.github/workflows/lint.yaml
.github/workflows/test.yaml
charts/signoz/templates/_clickhouse.tpl
charts/signoz/templates/otel-collector-metrics/deployment.yaml
charts/signoz/templates/otel-collector/deployment.yaml
charts/signoz/templates/query-service/statefulset.yaml

Support for secure clickhouse in SigNoz chart.
_Note: We will need to make changes in query-service and otel-collector exporters. Tracking issue: [here](https://github.com/SigNoz/engineering-pod/issues/773)._

Support for secure clickhouse in SigNoz chart

---

charts/signoz/Chart.yaml
charts/signoz/templates/NOTES.txt
charts/signoz/values.yaml

Fixes #95 
-  fix ingress hostname in post install NOTES 
- fix default values.yaml:
- disable `installCRDs` of `cert-manager`
- include `postgresPassword` configuration for `keycloak`

fix default values.yaml and ingress hostname in post install NOTES

---

charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/_config.tpl
charts/k8s-infra/templates/_helpers.tpl
charts/k8s-infra/templates/otel-agent/configmap.yaml
charts/k8s-infra/templates/otel-agent/daemonset.yaml
charts/k8s-infra/templates/otel-deployment/configmap.yaml
charts/k8s-infra/templates/otel-deployment/deployment.yaml
charts/k8s-infra/values.yaml

- Set up `otelcol` config using templates while supporting any provided base config from `values.yaml` intact
- Include `k8sattributes` processor
- Log collection:
- Option to enable/disable
- Blacklist specific namespace, pod, or container
- Root level option to whether skip verifying insecure certificates
- Root level option to enable/disable: kubelet metrics (agent), hostmetrics (agent), and cluster metrics (deployment)

k8s-infra: easily control OtelCollector config using presets

---

charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/_config.tpl
charts/k8s-infra/values.yaml

- Kubelet preset configurations: `authType` and `endpoint`
- Log preset configurations: `include`, `operators` and `podAssociation`
- `sources` removed from pod association option

chore: 🔧 improve preset configurations

---

charts/signoz/values.yaml

There's a limit of 15 characters when creating a service in kubernetes. Prometheus-metrics exceeds this limits. 
Renaming it to solve.

Fix character limit when setting prometheus receiver

---

charts/k8s-infra/templates/_config.tpl
charts/k8s-infra/values.yaml

Configuration to set up metrics groups and extra metadata labels.
By default enable following `metricGroups`:
- container
- pod
- node
- volume

k8s-infra: improve kubeletstats receiver

---

charts/signoz/values.yaml

chore: 🔧 remove init container label from scrapped metrics

---

charts/k8s-infra/values.yaml

The k8sattribute processor adds to attributes by default, so it can override this and there will be no duplicates.

Move to attributes instead of resources.

---

charts/signoz/Chart.yaml
charts/signoz/templates/_helpers.tpl
charts/signoz/templates/alertmanager/services.yaml
charts/signoz/templates/alertmanager/statefulset.yaml
charts/signoz/templates/frontend/service.yaml
charts/signoz/templates/query-service/service.yaml
charts/signoz/templates/query-service/statefulset.yaml
charts/signoz/values.yaml

Tested the changes:
```
$ kubectl exec -n platform -it signoz-alertmanager-0 -- sh
Defaulted container "signoz-alertmanager" out of: signoz-alertmanager, signoz-alertmanager-init (init)
/alertmanager $ wget -q -O - signoz-query-service:8085/api/v1/channels
{"status":"success","data":[]}
```

fix: resolve alertmanager internal port issue

---

charts/clickhouse/templates/_helper.tpl

If trying to render clickhouse with the following
```bash
helm template charts/clickhouse -f broken-values.yaml
```
and the values.yaml
```yaml
files:
config.d/log_rotation.xml: |
<clickhouse>
<logger>
<level>xxx</level>
<console>true</console>
<errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
<log>/var/log/clickhouse-server/clickhouse-server.log</log>
<size>100M</size>
<count>10</count>
</logger>
</clickhouse>
```
helm unindentds and break the output yaml
```
coalesce.go:175: warning: skipped value for zookeeper.initContainers: Not a table.
Error: YAML parse error on clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml: error converting YAML to JSON: yaml: line 77: could not find expected ':'
```

fix: Fix rendering error when clickhouse files are specified

---

charts/signoz/values.yaml

chore(otel-config): 🔧 remove k8sattr and resourcedetection processors from otlp pipeline

---

charts/k8s-infra/templates/_config.tpl

Path for a container log is something like:
```
"/var/log/pods/platform_mon-signoz-otel-collector-dffb45dbb-r9c6r_e951d249-f208-47f3-aa35-81a096ba2ade/istio-proxy/0.log"
```
The existing rule:
```
/var/log/pods/{{ .Release.Namespace }}_*.log
```
excludes log files files in /var/log/pods rather than the container pod logs.
Fixes: https://github.com/SigNoz/charts/issues/193

fix(signoz): match correct path for namespace exclusion

---

charts/signoz/values.yaml

The clickhouse logging config belongs under clickhouseOperator (see "clickhouse" chart), but it is incorrectly under the "initContainers" key in the signoz default values.yaml

Fix incorrect default values file

---

charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/_config.tpl
charts/k8s-infra/templates/otel-agent/daemonset.yaml
charts/k8s-infra/templates/otel-deployment/deployment.yaml
charts/k8s-infra/values.yaml
charts/signoz/templates/otel-collector-metrics/deployment.yaml
charts/signoz/templates/otel-collector/deployment.yaml

- deprecated `host_name` for K8s in favour of `k8s_node_name`
- in `filelog`, used `add` operator with `env` expression to include `k8s_cluster_name`
- removed `resourcedetection` processor from pipelines with OTLP receivers
- created `resourcedetection/internal` for `env` detector in `otelAgent` and `otelDeployment`
- more options for logging exporter
- enabled pprof extension in otelAgent but the ports not enabled by default
- removed `k8sattributes` and `resourcedetection` processors as well as `hostmetrics` receiver from `otelDeployment`
Commands to generate complete configs of `otelAgent` and `otelDeployment`:
```bash
helm template charts/k8s-infra -s templates/otel-agent/configmap.yaml > otel-agent-config.yaml
helm template charts/k8s-infra -s …
```

chore(k8s-infra): 🔧  otel-collector config changes

---

charts/clickhouse/Chart.yaml
charts/clickhouse/templates/clickhouse-operator/deployment.yaml
charts/clickhouse/values.yaml
charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/otel-agent/daemonset.yaml
charts/k8s-infra/templates/otel-deployment/deployment.yaml
charts/k8s-infra/values.yaml
charts/signoz/templates/otel-collector-metrics/deployment.yaml
charts/signoz/templates/otel-collector/deployment.yaml
charts/signoz/values.yaml

- pod annotations changes like formatting and removal of default `/metrics` path annotations
- use `metrics/internal` instead of `metrics/general` in otelCollector config

disable default metrics scraping in dependency charts

---

charts/signoz/templates/query-service/statefulset.yaml
charts/signoz/values.yaml

I've added the ability to add  additional environment variables for the query service. This is needed for our setup to be able to set the CONTEXT_TIMEOUT environment variable added by a coleague of mine in https://github.com/SigNoz/signoz/commit/dcad77746ae68d411319bdd60d29e1f1b4cddff1

feat: Added ability to add additional environment variables for the query service

---

charts/signoz/templates/query-service/statefulset.yaml

Reverts SigNoz/charts#287
I remembered why we don't want to have prefer-delta true in charts. For our customers, we need to have two pipelines - one each for delta and cumulative and let the data be populated for some time. Then, we remove the cumulative pipeline and set the prefer-delta to true. This is the smooth way to roll out this change: https://github.com/SigNoz/signoz/issues/3579. Otherwise, people won't be able to see data fully.

Revert "chore(query-service): 🔧 include prefer-delta flag"

---

charts/signoz/Chart.yaml
charts/signoz/templates/alertmanager/statefulset.yaml

With single replica of Alertmanager it is failing to start without argument --cluster.advertise-address=$(POD_IP):{{ $svcClusterPort }}
More info: https://github.com/SigNoz/charts/issues/283

FIX: Alertmanager - Add arg cluster.advertise-address at all times

---

charts/signoz/Chart.yaml
charts/signoz/templates/otel-collector/schema-migrator-job.yaml
charts/signoz/values.yaml

chore: 🔧 migrator Job cleanup using ttlSecondsAfterFinished

---

.github/workflows/lint.yaml
.github/workflows/test.yaml

Suddenly, charts CI tests are failing due to cosign unavailability.
_Screenshot:_

ci(chart-testing): 👷 bump up actions and related components

---

charts/signoz/values.yaml

It's better to show how to create one in pipelines and then add a default one (disabled) in the pipelines which user can modify according to requirements.

fix: remove default trace_parser

---

charts/signoz/templates/_helpers.tpl
charts/signoz/templates/otel-collector-metrics/deployment.yaml
charts/signoz/templates/otel-collector/deployment.yaml
charts/signoz/templates/otel-collector/schema-migrator-job.yaml

This will delete old job using hooks before creation of new job for schema-migrator.
Pros: Clean up old migrator job on its own.
Cons: Uses static job name. Deletes old job before re-creating the job with same name for each `helm upgrade` or equivalent.

fix(migrator-job): schema migrator job cleanup

---

charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/otel-agent/daemonset.yaml
charts/k8s-infra/values.yaml

Fixes #347 
In order to use the `env` resource detector you need to be able to set the `OTEL_RESOURCE_ATTRIBUTES` env var, and at present it is hard-coded. This PR makes it a value.

Make OTEL_RESOURCE_ATTRIBUTES a value

---

charts/signoz/Chart.yaml
charts/signoz/templates/otel-collector/schema-migrator-job.yaml

The previous hooks `pre-install,pre-upgrade` only works for those upgrading from existing signoz installation but not new ones.

chore(migrator-job): use post install/upgrade helm hooks

---

charts/k8s-infra/values.yaml
charts/signoz/values.yaml

Not all k8s deployments resolve the node host name to an IP. This is
generally true inside of cloud providers, but not necessarily the case
when self-hosting.
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22843

otel-agent: collect kubelet stats from host IP

---

.github/workflows/test.yaml
charts/signoz/templates/_helpers.tpl
charts/signoz/templates/otel-collector-metrics/deployment.yaml
charts/signoz/templates/otel-collector/deployment.yaml
charts/signoz/templates/schema-migrator/migrations-upgrade.yaml
charts/signoz/templates/schema-migrator/migrations.yaml
charts/signoz/values.yaml

- default init migrator job runs on Helm install
- upgrade migrator job runs on Helm upgrade
- this should ideally fix the failing CI tests
Related to the issue resolved by Kong: https://github.com/helm/charts/pull/9047

chore(schema-migrator): separate migration jobs for install/upgrade

---

charts/signoz/values.yaml

This PR Fixes wrong key `existingClickhouse` to `externalClickhouse` at comment of `externalClickhouse.password`.

fix(typo): existingClickhouse comment to externalClickhouse

---

charts/signoz/values.yaml

The context timeout could cause the abrupt connection closing and cause broken pipe errors. I don't have much idea as to why the default 5s is not enough. This adjusts the setting to a little higher till I get to figure out the underlying reason.
Part of https://github.com/SigNoz/engineering-pod/issues/1148

Add timeout for clickhousemetricswrite

---

charts/clickhouse/values.yaml
charts/signoz/values.yaml

This helps to shorten the time to change ownership and permission of a volume.
When you have lots of files in the volume, it could fail to mount with `timed out waiting for the condition` error.
This change should help resolve it. 
> OnRootMismatch: Only change permissions and ownership if the permission and the ownership of root directory does not match with expected permissions of the volume. This could help shorten the time it takes to change ownership and permission of a volume.
Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

chore(clickhouse): set OnRootMismatch file system change policy

---

charts/k8s-infra/templates/otel-agent/service.yaml
charts/k8s-infra/values.yaml

When sending traces to the agent via the service it is necessary to route to the agent on the same host as the sending pod so that the k8s resource can look up the IP address and augment the data.
Kubernetes 1.26 introduced [internalTrafficPolicy](https://kubernetes.io/docs/reference/networking/virtual-ips/#internal-traffic-policy) to enabled this

Set internalTrafficPolicy on agent service when supported

---

charts/k8s-infra/Chart.yaml
charts/k8s-infra/values.yaml

chore(k8s-infra): tolerate all nodes in otel-agent daemonset as default

---

charts/signoz/Chart.yaml
charts/signoz/README.md
charts/signoz/values.yaml

This PR releases the support for ClickHouse cluster with multiple replicas, not just shard.
It is not enabled by default. To enable:
```yaml
...
clickhouse:
layout:
replicasCount: 2
schemaMigrator:
enableReplication: true
```
_Note: Multiple replicas increases the availability of the ClickHouse cluster however it incurs additional resource cost. **Proceed with caution!**_

chore(signoz): 📌 pin versions: SigNoz OtelCollector v0.88.19

---

charts/signoz/README.md
charts/signoz/templates/schema-migrator/migrations-init.yaml
charts/signoz/templates/schema-migrator/migrations-upgrade.yaml
charts/signoz/values.yaml

add scheduler hints to the schema migrator templates for init and upgrade in the form of `schemaMigrator.nodeSelector` `schemaMigrator.tolerations` and `schemaMigrator.nodeAffinity`.
fixes #428

feat: add scheduler hints for SchemaMigrator

---

charts/clickhouse/values.yaml
charts/signoz/Chart.yaml
charts/signoz/README.md
charts/signoz/templates/_clickhouse.tpl
charts/signoz/templates/query-service/configmap.yaml
charts/signoz/templates/schema-migrator/migrations-init.yaml
charts/signoz/templates/schema-migrator/migrations-upgrade.yaml
charts/signoz/values.yaml

Pin latest version of SigNoz OtelCollector `0.88.21` and update ClickHouse dsn as per latest parsing logic
- https://github.com/SigNoz/signoz-otel-collector/pull/294

chore: pin SigNoz OtelCollector 0.88.21 and update ClickHouse dsn

---

charts/k8s-infra/templates/_config.tpl

- Removes deprecated `Bearer` annotation for pushing to signoz

fix(k8s-infra): remove deprecated Bearer header

---

charts/k8s-infra/values.yaml
charts/signoz/Chart.yaml
charts/signoz/README.md
charts/signoz/values.yaml

Release PR:
- bump up `frontend` and `query-service` to `0.48.0`
- bump up `otel-collector`, `otel-collector-metrics` and `schema-migrator` to `0.102.0`

Release/signoz 0.44.0

---

charts/clickhouse/Chart.yaml
charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml
charts/clickhouse/values.yaml
charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/otel-deployment/deployment.yaml
charts/k8s-infra/values.yaml
charts/signoz/templates/schema-migrator/migrations-init.yaml
charts/signoz/templates/schema-migrator/migrations-upgrade.yaml
charts/signoz/values.yaml

- include topologySpreadConstraints for all remaining components: clickhouse, otel-deployment, and schema migrator. 
- bump up clickhouse to `24.1.1`
- bump up k8s-infra to `0.11.7`

chore: include topologySpreadConstraints for all components

---

charts/signoz/values.yaml

This change
- Enables metrics collection
- Changes log level from `ERROR` to `INFO`
- Uses the admin endpoint for probes as described in https://github.com/bitnami/charts/tree/main/bitnami/zookeeper#configure-log-level

Update ZooKeeper values

---

charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/_config.tpl
charts/k8s-infra/templates/otel-agent/daemonset.yaml

- otel-agent: mount root path in /hostfs for hostmetrics
- bump up k8s-infra to 0.11.8

fix(otel-agent): mount root path in /hostfs for hostmetrics

---

charts/clickhouse/Chart.yaml
charts/clickhouse/templates/clickhouse-operator/deployment.yaml
charts/clickhouse/values.yaml

- include deployment annotations for clickhouse operator
- include default hook-weight of -5

chore(ch-operator): include deployment annotations

---

charts/signoz/Chart.yaml
charts/signoz/README.md
charts/signoz/templates/NOTES.txt
charts/signoz/values.yaml

- Release SigNoz v0.52.0
- Bump up SigNoz OtelCollector v0.102.4
- Note about K8s-infra dependency removal from SigNoz chart

Release/signoz 0.50.0

---

.github/workflows/test.yaml
charts/k8s-infra/values.yaml

The decision to change the default settings for logging and OTLP exporters, reportedly due to CI concerns, seems misguided. The OTLP exporter should remain enabled by default. Users of k8s-infra should have their data collected and sent to SigNoz or other OTLP backends. With current defaults, users will not have any idea that their data is being collected but not sent anywhere.
Being able to perform simple install and provide an endpoint to send data is a great onboarding experience and we should strive to keep the experience simple with sensible defaults.

Fix values for k8s-infra

---

charts/clickhouse/Chart.yaml
charts/clickhouse/values.yaml

- remove hook weight for clickhouse operator
This was added for clean installation and deletion of the resources of clickhouse operator.
However this seems to depend on other dependent resources as well which would require the same helm hooks weight added to each of them.

fix(clickhouse): remove hook weight for chOperator

---

charts/signoz/Chart.yaml
charts/signoz/templates/otel-collector/keda-autoscaler.yaml
charts/signoz/values.yaml

The otelcollector has a hook weight of 3 but the scaledobjects have no hook weight. This is leading to the scaledobjects being created first which is leading to the error that the otelcollector deployment does not exist. 
This PR puts the hook weight of scaledobjects to > 3.

fix(autoscaling): add hook-weight annotation to keda autoscaler

---

charts/k8s-infra/templates/_config.tpl
charts/k8s-infra/values.yaml

- **New Features**
- Enhanced configuration for `kubeletMetrics` to allow additional metrics specification.
- Introduced new metrics for monitoring Kubernetes pod resource utilization: CPU limit, CPU request, memory limit, and memory request, all enabled by default.
These updates improve monitoring and observability capabilities within Kubernetes environments.

feat(metrics): add k8s request and limits

---

charts/k8s-infra/Chart.yaml

- **New Features**
- Updated the Helm chart version for `k8s-infra` to 0.11.11

chore(k8s-infra): bump to 0.11.11

---

charts/k8s-infra/Chart.yaml
charts/k8s-infra/templates/_config.tpl
charts/k8s-infra/templates/otel-agent/daemonset.yaml
charts/k8s-infra/values.yaml

- Introduced a new `k8snode` detector to add k8s.node.uid for hostmetrics.
- Updated logging configuration to the new streamlined container parser for better maintainability.
- The removal of k8s.pod.uid and k8s.pod.ip attributes and the inclusion of k8s.node.name attribute instead should resolve the interference issue with the k8sprocessor and improve its ability to match and enrich telemetry data accurately.
- Incremented Helm chart version and OpenTelemetry collector image version for new features and improvements.

fix(k8s-infra): enable k8sattributes to match other information

---

charts/signoz/Chart.yaml
charts/signoz/README.md
charts/signoz/values.yaml

- release SigNoz v0.56.0
- bump up SigNoz OtelCollector v0.102.12
- keep Schema Migrator version intact v0.102.10

Release/signoz 0.54.0

---

charts/signoz/templates/otel-collector/deployment.yaml

Removing `SIGNOZ_COMPONENT`, `K8S_CLUSTER_NAME` and `OTEL_RESOURCE_ATTRIBUTES` from the otel-collector.

chore(otel-collector): remove redundant env variables
